version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: retail-system
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mudasir434
      POSTGRES_DB: retail-system
    ports:
      - "5432:5432"
    volumes:
      - retail-system-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d retail-system"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  retail-system-data:
